version: '3'
services:

  ##########################
  ### REACTJS ##############
  ##########################

  node:
    image: node:8.9-alpine
    working_dir: /app
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:app.docker.localhost'
    expose:
      - "3000"
    volumes:
      - ./reactjs:/app
    command: sh -c 'yarn install'
     #&& yarn run start:dev'

  ##########################
  ### DRUPAL ###############
  ##########################

  # Here we use almost out of the box docker4drupal configuration.
  # So you can refer to their documentation for configuration.
  # You can add more containers for memcached, redis, varnish, solr, etc
  # using pre-built docker images.
  # https://github.com/wodby/docker4drupal/blob/master/docker-compose.yml

  php:
    image: wodby/drupal-php:7.1-2.4.3
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting below
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'          # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./drupal:/var/www/html
      # - d4d-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

  # nginx container.
  # name of container matches the URL of the site in order to be
  # able to make requests from node server by http to the backend
  # server using the same name as frontend.
  app.docker.localhost:
    image: wodby/drupal-nginx:8-1.13-2.4.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_SERVER_EXTRA_CONF_FILEPATH: /var/www/html/drupal-server.conf
    volumes:
      - ./drupal:/var/www/html
      # Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
      # - codebase:/var/www/html:cached # User-guided caching
      # - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:app.docker.localhost;PathPrefix:/admin'

  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./drupal/mysql/init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./drupal/mysql/data:/var/lib/mysql # I want to manage volumes manually.

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.docker.localhost'

  ##########################
  ### REVERSE PROXY ########
  ##########################

  traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Docker-sync for macOS users
#volumes:
#  d4d-unison-sync:
#    external: true
