<?php

/**
 * @file
 * Install, update and uninstall functions for the module.
 */

use Drupal\consumers\Entity\Consumer;

/**
 * Implements hook_install().
 */
function anu_auth_install() {
  // Create a Consumer.
  $client = Consumer::create([
    'uuid' => 'your_client_id',
    'owner_id' => 1,
    'user_id' => 1,
    'label' => 'Anu-LMS',
    'secret' => 'your_client_secret',
    'confidential' => TRUE,
  ]);
  $client->save();
}
