<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;

/**
 * @file
 * Contains hooks definition for Anu Comments module.
 */

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function anu_comments_paragraph_comment_access(EntityInterface $comment, $operation,  AccountInterface $account) {

  // Load the user object with all fields.
  $user = \Drupal\user\Entity\User::load($account->id());

  // Get value of the current user organization.
  $user_organization = null;
  if ($user->hasField('field_organization')) {
    $value = $user->get('field_organization')->getValue();
    $user_organization = !empty($value[0]['target_id']) ? $value[0]['target_id'] : null;
  }

  // Get value of the commeªnt's organization in which the comment had been
  // left off.
  $comment_organization = null;
  if ($comment->hasField('field_comment_organization')) {
    $value = $comment->get('field_comment_organization')->getValue();
    $comment_organization = !empty($value[0]['target_id']) ? $value[0]['target_id'] : null;
  }

  // We do not allow users from different organization has any access to the
  // comments from other organizations. In the other scenario we fallback to
  // other Drupal access checks.
  return $user_organization == $comment_organization ? AccessResult::neutral() : AccessResult::forbidden();
}
