# Schema for the views plugins of the module.

views.filter.user_allowed_roles:
  type: views.filter.many_to_one
  label: 'Allowed roles'

views.filter.anu_assigned_organizations:
  type: views.filter.many_to_one
  label: 'Assigned organizations'
