version: '2'
services:

  ##########################
  ### REACTJS ##############
  ##########################

  node:
    image: node:$NODE_TAG
    working_dir: /app
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:app.docker.localhost, app.docker.local'
    expose:
      - "3000"
    volumes:
      - ../reactjs:/app
    command: sh -c 'yarn install && yarn run start:dev'

  ##########################
  ### DRUPAL ###############
  ##########################

  php:
    image: wodby/drupal-php:$PHP_TAG
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - ../drupal:/var/www/html

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_SERVER_EXTRA_CONF_FILEPATH: /var/www/html/drupal-server.conf
    volumes:
      - ../drupal:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:app.docker.localhost, app.docker.local;PathPrefix:/admin'

  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ../drupal/mysql/data:/var/lib/mysql

  ##########################
  ### DONATIONS BACKEND ####
  ##########################

  solr:
    image: wodby/drupal-solr:$SOLR_TAG
    environment:
      SOLR_HEAP: 1024m
    volumes:
      - ../.platform/solr:/opt/solr/server/solr/maincore
    labels:
      - 'traefik.backend=solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.docker.localhost'

  #########################
  ### PhpMyAdmin ##########
  #########################

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.docker.localhost'

  #########################
  ### MAILHOG #############
  #########################

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.docker.localhost'

  #########################
  ### CODECEPTION #########
  #########################

  codecept:
    image: codeception/codeception
    depends_on:
      - chrome
      - nginx
    volumes:
      - ../tests/codeception:/project

  #########################
  ### CHROME FOR TESTS ####
  #########################

  chrome:
    image: selenium/standalone-chrome:3.11.0
    expose:
      - 4444
    shm_size: 2gb

  ##########################
  ### DOCKER MANAGEMENT ####
  ##########################

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.docker.localhost'

  ##########################
  ### REVERSE PROXY ########
  ##########################

  traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
        aliases:
          - app.docker.localhost
          - app.docker.local
