<?php

/**
 * @file
 * Module implementation file.
 */

use Drupal\user\Entity\User;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function anu_classes_group_access(EntityInterface $entity, $operation, AccountInterface $account) {
  // Process only class group type.
  if ($entity->bundle() != 'class') {
    return AccessResult::neutral();
  }

  $entity_organization_ids = $account_organization_ids = [];
  $account_entity = User::load($account->id());

  // Skip for users with proper permissions.
  if ($account_entity->hasPermission('manage classes from any organization')) {
    return AccessResult::neutral();
  }

  // Get organization ids from given class.
  if (!empty($entity->field_organization->getValue())) {
    $entity_organization_ids = array_column($entity->field_organization->getValue(), 'target_id');
  }

  // Get organization ids from current user.
  if (!empty($account_entity->field_organization->getValue())) {
    $account_organization_ids = array_column($account_entity->field_organization->getValue(), 'target_id');
  }

  // Allow an access for users assigned to same organizations.
  $intersect = array_intersect($entity_organization_ids, $account_organization_ids);
  if (!empty($intersect)) {
    return AccessResult::neutral();
  }

  // Forbid an access in any other cases.
  return AccessResult::forbidden();
}
