<?php

/**
 * @file
 * File with installation hooks for the module.
 */

use Drupal\user\Entity\Role;
use Drupal\user\Entity\User;

/**
 * Implements hook_module_preinstall().
 *
 * Delete existing test users if any.
 */
function anu_test_content_module_preinstall($module) {
  $users = anu_test_get_test_users();
  foreach ($users as $user) {
    user_delete($user->id());
  }
  if (isset($_ENV['PLATFORM_ENVIRONMENT']) &&  substr($_ENV['PLATFORM_ENVIRONMENT'], 0, 6) === 'master') {
    throw new Exception('anu_test_content module should never be enabled at production environment');
  }
}

/**
 * Implements hook_uninstall().
 */
function anu_test_content_uninstall() {
  anu_test_deactivate_test_users();
}

/**
 * Active test users on all development environments.
 */
function anu_test_activate_test_users() {

  /* @var $role \Drupal\user\Entity\Role */
  foreach (Role::loadMultiple() as $role) {

    if ($role->id() == 'anonymous') {
      continue;
    }

    $username = $role->id() . '.test';

    /* @var $account \Drupal\user\Entity\User */
    $account = user_load_by_name($username);
    if (empty($account)) {
      $account = User::create();
      $account->enforceIsNew();
      $account->setEmail('admin+' . $role->id() . '.test@anulms.com');
      $account->setUsername($role->id() . '.test');

      if ($role->id() !== 'authenticated') {
        $account->addRole($role->id());
      }

      drupal_set_message(t('User @username was created.', ['@username' => $account->getUsername()]));
    }
    else {
      $account->activate();
    }

    $account->setPassword('password');
    $account->save();
  }
}

/**
 * Deactivate test users on non-development environments.
 */
function anu_test_deactivate_test_users() {

  $users = anu_test_get_test_users();
  /* @var $user \Drupal\user\Entity\User */
  foreach ($users as $user) {
    $user->block();
    $user->save();
  }

}

/**
 * Load array of test users.
 *
 * @return \Drupal\Core\Entity\EntityInterface[]|static[]
 *   List of test users.
 */
function anu_test_get_test_users() {

  $ids = \Drupal::entityQuery('user')
    ->condition('name', '.test', 'ENDS_WITH')
    ->execute();
  $users = User::loadMultiple($ids);

  return $users;
}
